### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/osjs_ynh#10]
Hi,

Your app doesn't work on our CI and is currently level 0.
https://ci-apps.yunohost.org/jenkins/job/osjs%20(Community)/74/consoleFull

Your app will be moved at 'notworking' status by the end of this week, on May, 27 if nothing is done before to make it work.

**Comment by frju365** [comment]
Apparrentl-

**Comment by maniackcrudelis** [comment]
Broken again
https://ci-apps.yunohost.org/ci/job/2317

Please fix it before Saturday 13th

**Comment by yalh76** [comment]
package upgraded
