### ISSUE TITLE
'Cannot GET' if installed on path

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/osjs_ynh#16]
Installation is successful, however I am facing a `Cannot GET /osjs` when trying to access the app.

```
yunohost:
  repo: stable
  version: 3.2.2
```

`/var/log/osjs/osjs.log` is empty, and nginx's error log does not show anything related to OSjs.

I have just tried to install at the root of the domain, and OSjs loads correctly.

**Comment by Mrs-Feathers** [comment]
same error for me

**Comment by yalh76** [comment]
should work now
